const { buildSchema } = require('graphql')

const schema = buildSchema(`
    type Query {
        posts(token:String!): [Post]
    }

    type Mutation {
        createUser(name:String!, email:String!, password:String!):String!
        login(email:String!, password:String!):String
        createPost(token:ID!, author:String!, content:String!): Post!
        deletePost(_id:ID!):Post!
        # updatePost
    }

    type User {
        _id: ID!
        name: String!
        email: String!
        password: String!
    }

    type Post {
        _id: ID!
        token: ID
        author: String
        content: String
        likes: Int
        mutable: Boolean
    }
`)

module.exports = schema