const { buildSchema } = require('graphql')

const schema = buildSchema(`
    type Query {
        posts(token:String!): [Post!]
        login(email:String!, password:String!):String!
    }

    type Mutation {
        createUser(name:String!, email:String!, password:String!):String!
        createPost(token:ID!, content:String!): String
        deletePost(_id:ID!): String
        likedPost(_id:ID!, userToken: ID!) : String
    }

    type User {
        _id: ID!
        name: String!
        email: String!
        password: String!
    }

    type Post {
        _id: ID
        authorID: ID
        author: String
        content: String
        likes: String
        mutable: Boolean
    }

`)

module.exports = schema