const { buildSchema } = require('graphql')

const schema = buildSchema(`
    type Query {
        hello: [User!]
        # posts
    }

    type Mutation {
        createUser(name:String!, email:String!, password:String!):String!
        login(email:String!, password:String!):String
        createPost(authorID:ID!, author:String!, content:String!): Post!
        # deletePost
        # updatePost
    }

    type User {
        _id: ID!
        name: String!
        email: String!
        password: String!
    }

    type Post {
        authorID: ID!
        author: String!
        content: String!
        likes: Int
    }
`)

module.exports = schema